function(test_create_targets)
    _JSON_set(doxypress.general.output-dir "${CMAKE_CURRENT_BINARY_DIR}")
    _JSON_set(doxypress.output-html.generate-html true)
    _JSON_set(doxypress.output-latex.generate-latex true)
    TPA_set(GENERATE_PDF true)

    #add_custom_target(_test COMMAND "${CMAKE_COMMAND} --version")
    TPA_set(INPUT_TARGET main)
    TPA_set(TARGET_NAME "doxypress_docs")
    configure_file(DoxypressTest1.json
            ${CMAKE_CURRENT_BINARY_DIR}/DoxypressTest1.json @ONLY)
    _doxypress_add_targets(${PROJECT_SOURCE_DIR}/DoxypressTest1.json
            ${CMAKE_CURRENT_BINARY_DIR}/DoxypressTest1.json)
    _doxypress_add_open_targets(doxypress_docs "${CMAKE_CURRENT_BINARY_DIR}")

    if (NOT TARGET doxypress_docs)
        _doxypress_assert_fail("doxypress target `doxypress_docs` was not created")
    endif()
    if (NOT TARGET doxypress_docs.open_html)
        _doxypress_assert_fail("The target `doxypress_docs.open_html` was not created")
    endif()
    if (NOT TARGET doxypress_docs.open_latex)
        _doxypress_assert_fail("The target `doxypress_docs.open_latex` was not created")
    endif()
    if (NOT TARGET doxypress_docs.open_pdf)
        _doxypress_assert_fail("The target `doxypress_docs.open_pdf` was not created")
    endif()
endfunction()

test_create_targets()